version: 2
updates:
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/OuterInnerResource.Pn/OuterInnerResource.Pn"
  schedule:
    interval: daily
- package-ecosystem: nuget
  directory: "/eFormAPI/Plugins/OuterInnerResource.Pn/OuterInnerResource.Pn.Test"
  schedule:
    interval: daily